export const ROLES = Object.freeze({
  ADMIN: "ADMIN",
  RECEPTION: "RECEPTION",
  RESTAURANT_STAFF: "RESTAURANT_STAFF",
  HOUSEKEEPING: "HOUSEKEEPING",
  CUSTOMER: "CUSTOMER",
});

export const STAFF_ROLES = Object.freeze([
  ROLES.ADMIN,
  ROLES.RECEPTION,
  ROLES.RESTAURANT_STAFF,
  ROLES.HOUSEKEEPING,
]);
